import { type FileExtensions } from "~/types/client";

function strEnum<T extends string>(o: Array<T>): { [K in T]: K } {
  return o.reduce((res: { [K in T]: K }, key: T) => {
    res[key] = key;
    return res;
  }, Object.create(null) as { [K in T]: K });
}

export const transformGroups = [
  "web",
  "js",
  "scss",
  "css",
  "less",
  "html",
  "android",
  "compose",
  "ios",
  "ios-swift",
  "ios-swift-separate",
  "assets",
  "flutter",
  "flutter-separate",
  "react-native",
];

export const transformGroupsEnum = strEnum(transformGroups);

export const transforms = [
  "attribute/cti",
  "attribute/color",
  "name/human",
  "name/cti/camel",
  "name/ti/camel",
  "name/cti/kebab",
  "name/cti/snake",
  "name/cti/constant",
  "name/ti/constant",
  "name/cti/pascal",
  "color/rgb",
  "color/hsl",
  "color/hsl-4",
  "color/hex",
  "color/hex8",
  "color/hex8android",
  "color/composeColor",
  "color/UIColor",
  "color/UIColorSwift",
  "color/ColorSwiftUI",
  "color/css",
  "color/sketch",
  "size/sp",
  "size/dp",
  "size/object",
  "size/remToSp",
  "size/remToDp",
  "size/px",
  "size/rem",
  "size/remToPt",
  "size/compose/remToSp",
  "size/compose/remToDp",
  "size/compose/em",
  "size/swift/remToCGFloat",
  "size/remToPx",
  "size/pxToRem",
  "content/icon",
  "content/quote",
  "content/objC/literal",
  "content/swift/literal",
  "font/objC/literal",
  "font/swift/literal",
  "time/seconds",
  "asset/base64",
  "asset/path",
  "asset/objC/literal",
  "asset/swift/literal",
  "color/hex8flutter",
  "content/flutter/literal",
  "asset/flutter/literal",
  "font/flutter/literal",
  "size/flutter/remToDouble",
];

export const transformsEnum = strEnum(transforms);

export const formats = [
  "css/variables",
  "scss/map-flat",
  "scss/map-deep",
  "scss/variables",
  "scss/icons",
  "less/variables",
  "less/icons",
  "stylus/variables",
  "javascript/module",
  "javascript/module-flat",
  "javascript/object",
  "javascript/umd",
  "javascript/es6",
  "typescript/es6-declarations",
  "typescript/module-declarations",
  "android/resources",
  "android/colors",
  "android/dimens",
  "android/fontDimens",
  "android/integers",
  "android/strings",
  "compose/object",
  "ios/macros",
  "ios/plist",
  "ios/singleton.m",
  "ios/singleton.h",
  "ios/static.h",
  "ios/static.m",
  "ios/colors.h",
  "ios/colors.m",
  "ios/strings.h",
  "ios/strings.m",
  "ios-swift/class.swift",
  "ios-swift/enum.swift",
  "ios-swift/any.swift",
  "css/fonts.css",
  "json",
  "json/asset",
  "json/nested",
  "json/flat",
  "sketch/palette",
  "sketch/palette/v2",
  "flutter/class.dart",
];

enum fileExtensionsEnum {
  "css/variables" = "css",
  "scss/map-flat" = "scss",
  "scss/map-deep" = "scss",
  "scss/variables" = "scss",
  "scss/icons" = "scss",
  "less/variables" = "less",
  "less/icons" = "less",
  "stylus/variables" = "styl",
  "javascript/module" = "js",
  "javascript/module-flat" = "js",
  "javascript/object" = "js",
  "javascript/umd" = "js",
  "javascript/es6" = "js",
  "typescript/es6-declarations" = "ts",
  "typescript/module-declarations" = "ts",
  "android/resources" = "xml",
  "android/colors" = "xml",
  "android/dimens" = "xml",
  "android/fontDimens" = "xml",
  "android/integers" = "xml",
  "android/strings" = "xml",
  "compose/object" = "kt",
  "ios/macros" = "m",
  "ios/plist" = "plist",
  "ios/singleton.m" = "m",
  "ios/singleton.h" = "h",
  "ios/static.h" = "h",
  "ios/static.m" = "m",
  "ios/colors.h" = "h",
  "ios/colors.m" = "m",
  "ios/strings.h" = "h",
  "ios/strings.m" = "m",
  "ios-swift/class.swift" = "swift",
  "ios-swift/enum.swift" = "swift",
  "ios-swift/any.swift" = "swift",
  "css/fonts.css" = "css",
  "json" = "json",
  "json/asset" = "json",
  "json/nested" = "json",
  "json/flat" = "json",
  "sketch/palette" = "sketchpalette",
  "sketch/palette/v2" = "sketchpalette",
  "flutter/class.dart" = "dart",
}

export const fileExtensions: FileExtensions = {
  ...fileExtensionsEnum,
};

export const formatsEnum = strEnum(formats);

export const sdBuildFolder = `${
  process.env.NODE_ENV === "development" ? "" : "/"
}tmp/sd-build/`;

export const host = `${
  process.env.NODE_ENV === "development" ? "http://" : "https://"
}${process.env.HOST_URL as string}`;
